name: ExcellentShop
main: su.nightexpress.nexshop.ShopPlugin
version: '${project.version}'
description: Advanced 4 in 1 shop plugin with a lot of cool features!
author: NightExpress
depend: [ nightcore ]
softdepend:
  - Vault
  - CoinsEngine
  - PlayerPoints
  - GemsEconomy
  - UltraEconomy
  - BeastTokens
  - VotingPlugin
  - EliteMobs
  - Citizens
  - WorldGuard
  - Lands
  - HuskClaims
  - Kingdoms
  - AdvancedRegionMarket
  - GriefPrevention
  - Oraxen
  - ItemsAdder
  - MMOItems
  - PlaceholderAPI
api-version: 1.18
